### ISSUE TITLE
examples/debug crash the pic

### ISSUE THREAD

**Issue by jordanpenard** [mtusnio/LetMeCreateIoT#3]
Hi,
I'm trying to run `examples/debug`, but I'm facing a few issues.

1) When I build the example I get

```
main.co: In function `process_thread_main_process':
main.c:(.text.process_thread_main_process+0xf4): undefined reference to `__init_debug_connection'
main.c:(.text.process_thread_main_process+0x144): undefined reference to `__network_printf'
main.c:(.text.process_thread_main_process+0x194): undefined reference to `__network_printf'
main.c:(.text.process_thread_main_process+0x1dc): undefined reference to `__network_printf'
```

To fix that I had to add 

``` c
#include "letmecreate/core/debug.c"
#include "letmecreate/core/network.c"
```

2) INIT_NETWORK_DEBUG is causing the PIC to crash and reboot. I modified the code as follow

``` c
#ifdef DEBUG_IP
  leds_on(LED1);
  leds_off(LED2);
#endif

INIT_NETWORK_DEBUG();
{

  #ifdef DEBUG_IP
    leds_on(LED2);
    leds_off(LED1);
  #endif
```

But the only thing I see is LED1 flashing (ON at boot thanks to "leds_on(LED1);" and then OFF due to the reboot of the PIC I guess)

**Comment by mtusnio** [comment]
Hello!

1) I'll build this tonight and see what's wrong, I've just had a quick look at Travis and the build seems to be passing. Can you run xc32-gcc --version and let me know what's your Microchip compiler version in the meantime?

2) What's your programming method, is it Avrdude? There's an outstanding patch to disable Contiki watchdog with Avrdude, and this looks like an issue with the watchdog reboot after the INIT_NETWORK_DEBUG macro yields the process.

**Comment by jordanpenard** [comment]
1) 

```
MBP-de-Jordan:dev jordan$ xc32-gcc --version
xc32-gcc (Microchip Technology) 4.5.2 MPLAB XC32 Compiler v1.34 Build date: Nov 21 2014
Part support version: 1.34 (A)
```

2) Yes I'm using avrdude. Ho ok, what can I do to disable the watchdog for now? I did some more analysis now that I have a working UART, and I found that the crash was caused by `PROCESS_WAIT_UDP_CONNECTED()`.

**Comment by mtusnio** [comment]
1) Regarding the fail, have you by any chance compiled the example before installing the library? Try running make clean on the example just to see if it's an issue with the source files not being detected properly until you included them manually. 

2) I haven't been able to verify if this patch works yet, but you can give it a go and see if it fixes the issue for you. You can apply this patch on top of your Contiki creator branch and re-run make clean && make to see if it helps.
https://github.com/mtusnio/contiki/commit/95ef66b25513cfe9464d8ed7ec4058b8c8946c3a.patch

**Comment by jordanpenard** [comment]
1) I'm cleaning each time I'm building. Try `grep -r "network\.c" .` from the top of LetMeCreateIoT, there isn't anything including the .c file. And there is the same issue with the lib debug as well if I remember well.

2) The patch is working ✅

**Comment by mtusnio** [comment]
I'll open up a PR for the patch then, thanks for testing it out! :)

Network.c should not be included anywhere since it's a source file, the Makefile for Contiki gets modified to include the proper source files however. There are two possible issues:

1)  Have you reverted the Makefile.include in Contiki? The library modifies the file to include additional files as part of the install process, can you run git diff Makefile.include in root Contiki folder and paste the results? 

2) You mentioned above you'd done some changes, can you paste the source file? It's possible there's some conflict with includes.

**Comment by jordanpenard** [comment]
Hum... my `contiki/Makefile.include` is identical to the one in git, it hasn't been updated. I just re-ran `install.sh ../contiki` but this isn't changing anything to `contiki/Makefile.include`.
Actually, now that the watchdog issue is solved, I reverted all my changes, so the only changes I have now are the 2 includes added in `examples/debug/main.c`.

**Comment by mtusnio** [comment]
The install instructions have changed recently, try running `./install.sh -p ../contiki`, this should print a bunch of lines of messages about various directories being installed and patches applied, as well as a confirmation that the install worked.

**Comment by jordanpenard** [comment]
Still the same. I can see that the install created a `contiki/Makefile.include-e` which is identical to `contiki/Makefile.include` which is still identical to the git version.

```
MBP-de-Jordan:LetMeCreateIoT jordan$ ./install.sh -p ../contiki
Installing the library files to /Users/jordan/Documents/ci40/contiki
Creating staging dir
Cloning into '/Users/jordan/Documents/ci40/LetMeCreateIoT/feeds_tmp'...
remote: Counting objects: 2511, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2511 (delta 3), reused 0 (delta 0), pack-reused 2500
Receiving objects: 100% (2511/2511), 684.33 KiB | 206.00 KiB/s, done.
Resolving deltas: 100% (1481/1481), done.
Checking connectivity... done.
Applying patch 7seg.patch
Applying patch air_quality.patch
Applying patch alcohol.patch
Applying patch bargraph.patch
Applying patch color.patch
Applying patch color2.patch
Applying patch common.patch
Applying patch ir_distance.patch
Applying patch ir_eclipse.patch
Applying patch joystick.patch
Applying patch led_matrix.patch
Applying patch motion.patch
Applying patch proximity.patch
Applying patch relay.patch
Applying patch relay2.patch
Applying patch thermo3.patch
Adding LMC core module to Contiki makefile...
Adding LMC click module to Contiki makefile...
Creating symbolic link...
Library installed successfully
Cleared staging dir
```

**Comment by mtusnio** [comment]
For now I think you can try just applying this diff on top of Contiki - https://gist.github.com/mtusnio/ae227437b259b27327dc387eabf49053 - and the example should compile with the proper files.

I'll look into it since it seems that there's some issue in the install process. Can you just provide me this information:
- What OS are you using?
- Can you send the result of `ls -l` in both Contiki and LetMeCreateIoT?

**Comment by jordanpenard** [comment]
Ok the patch did the trick, thanks.
I'm running on the latest Mac OS

```
MBP-de-Jordan:debug jordan$ uname -a
Darwin MBP-de-Jordan 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin
```

```
MBP-de-Jordan:ci40 jordan$ ll contiki/
total 56K
-rw-r--r--  1 jordan  13K Oct  8 01:15 CONTRIBUTING.md
-rw-r--r--  1 jordan 2.0K Oct  8 01:15 LICENSE
-rw-r--r--  1 jordan 8.0K Oct  9 20:01 Makefile.include
-rw-r--r--  1 jordan 7.9K Oct  9 19:39 Makefile.include-e
-rw-r--r--  1 jordan 4.6K Oct  8 01:15 README-BUILDING.md
-rw-r--r--  1 jordan 6.2K Oct  8 01:15 README-EXAMPLES.md
-rw-r--r--  1 jordan  836 Oct  8 01:15 README.md
drwxr-xr-x 35 jordan 1.2K Oct  8 01:15 apps/
drwxr-xr-x 15 jordan  510 Oct  9 19:39 core/
drwxr-xr-x 16 jordan  544 Oct  8 01:15 cpu/
drwxr-xr-x  8 jordan  272 Oct  8 01:15 dev/
drwxr-xr-x 32 jordan 1.1K Oct  8 01:15 doc/
drwxr-xr-x 49 jordan 1.7K Oct  8 01:15 examples/
drwxr-xr-x 34 jordan 1.2K Oct  8 01:15 platform/
drwxr-xr-x 29 jordan  986 Oct  8 01:15 regression-tests/
drwxr-xr-x 46 jordan 1.6K Oct  8 15:28 tools/
```

```
MBP-de-Jordan:ci40 jordan$ ll LetMeCreateIoT/
total 32K
-rw-r--r--  1 jordan  455 Oct  8 17:28 Doxyfile
-rw-r--r--  1 jordan 1.5K Oct  8 17:28 LICENSE
-rw-r--r--  1 jordan 4.6K Oct  8 17:28 README.md
lrwxr-xr-x  1 jordan   36 Oct  9 19:39 contiki -> /Users/jordan/Documents/ci40/contiki/
drwxr-xr-x 14 jordan  476 Oct  8 17:28 examples/
-rw-r--r--  1 jordan    7 Oct  8 17:28 feed
drwxr-xr-x  3 jordan  102 Oct  8 17:28 feeds/
drwxr-xr-x  7 jordan  238 Oct  9 19:39 include/
-rwxr-xr-x  1 jordan 6.5K Oct  8 17:28 install.sh*
drwxr-xr-x  5 jordan  170 Oct  8 17:28 scripts/
drwxr-xr-x  4 jordan  136 Oct  9 19:39 src/
drwxr-xr-x  3 jordan  102 Oct  9 18:02 tests/
```

**Comment by mtusnio** [comment]
Thanks, I think I see the issue. I'll let you know once I've fixed it.

**Comment by mtusnio** [comment]
I've pushed 1bb09f9 which should make the install script both GNU & BSD sed compatible, it's currently in the dev branch. Can you switch the dev and pull the changes to see if it works on your end?

**Comment by mtusnio** [comment]
@jordanpenard, did you have a moment to rerun the script and see if it works?

**Comment by jordanpenard** [comment]
@mtusnio : All good, the install script is working properly now, you can merge into master

**Comment by mtusnio** [comment]
Thanks! I've merged it in, I'll close the issue for now.
